apiVersion: secrets-store.csi.k8s.io/v1
kind: SecretProviderClass
metadata:
  name: akv-app-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "<managed-identity-client-id>"
    keyvaultName: "<keyvault-name>"
    tenantId: "<tenant-id>"
    objects: |
      array:
        - | 
          objectName: <app-secret-name>
          objectType: secret
          objectVersion: ""
        - |
          objectName: <db-connection-string>
          objectType: secret
          objectVersion: ""
  secretObjects:
    - secretName: app-secrets
      type: Opaque
      data:
        - key: APP_SECRETS
          objectName: <app-secret-name>
        - key: DB_CONNECTION_STRING
          objectName: <db-connection-string>